name: aws secrets manager

on:
  push:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  getsecrets:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: 'ap-northeast-1'
          role-to-assume: ${{ secrets.AWS_ROLE }}
      - name: Get secrets by name and by ARN
        uses: aws-actions/aws-secretsmanager-get-secrets@v2
        with:
          secret-ids: |
            ${{ secrets.SSM_ARN }}
            testplainkey
          parse-json-secrets: true
      - name: Run a one-line script
        run: bash env.sh
